# Generated by Django 3.1b1 on 2020-07-20 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessLevel', models.CharField(choices=[('AL', 'Administrador'), ('NL', 'Normal'), ('LL', 'Limitado')], default='NL', max_length=3, verbose_name='Nivel de acceso')),
                ('locks', models.BooleanField(verbose_name='Bloqueado')),
                ('residenceName', models.CharField(max_length=30, verbose_name='Nombre de residencia')),
                ('streetBlockNumber', models.CharField(max_length=10, verbose_name='Numero de manzana')),
                ('homeNumber', models.CharField(max_length=4, verbose_name='Numero de casa')),
                ('enrollment', models.CharField(max_length=8, unique=True, verbose_name='Matrícula')),
                ('brandModel', models.CharField(max_length=35, verbose_name='Marca y modelo del carro')),
                ('color', models.CharField(max_length=15, verbose_name='Color del carro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usersdata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
