# Generated by Django 3.0.4 on 2020-05-22 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userHome', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessLevel', models.CharField(choices=[('AL', 'Administrador'), ('NL', 'Normal'), ('LL', 'Limitado')], default='NL', max_length=3, verbose_name='Nivel de acceso')),
                ('locks', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersdata', to='userHome.UserHome')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usersdata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
