# Generated by Django 3.0.4 on 2020-03-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='home',
        ),
    ]
