# Generated by Django 3.0.4 on 2020-06-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='enrollment',
            field=models.CharField(max_length=8, unique=True, verbose_name='Matrícula'),
        ),
    ]
