# Generated by Django 3.0.4 on 2020-03-13 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userHome', '0004_remove_userhome_userdata'),
        ('userData', '0002_remove_userdata_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userHome.UserHome'),
        ),
    ]
