# Generated by Django 3.0.4 on 2020-05-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0007_userdata_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='accesLevel',
            new_name='accessLevel',
        ),
    ]
