# Generated by Django 3.1b1 on 2020-07-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='Numero de Telefono'),
        ),
    ]
