# Generated by Django 3.1a1 on 2020-06-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.CharField(max_length=11, unique=True, verbose_name='Numero de Telefono'),
        ),
    ]
