# Generated by Django 3.0.4 on 2020-03-10 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0001_initial'),
        ('nums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='number',
            name='car_plate',
        ),
        migrations.RemoveField(
            model_name='number',
            name='house_num',
        ),
        migrations.RemoveField(
            model_name='number',
            name='street_num',
        ),
        migrations.RemoveField(
            model_name='number',
            name='user',
        ),
        migrations.AddField(
            model_name='number',
            name='userData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userData.UserData'),
        ),
    ]
