# Generated by Django 3.0.4 on 2020-03-21 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0003_userdata_home'),
        ('nums', '0002_auto_20200310_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='userData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nums', to='userData.UserData'),
        ),
    ]
