# Generated by Django 3.0.4 on 2020-03-22 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nums', '0003_auto_20200321_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='userData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nums', to=settings.AUTH_USER_MODEL),
        ),
    ]
