# Generated by Django 3.0.4 on 2020-03-22 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nums', '0004_auto_20200322_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='number',
            old_name='userData',
            new_name='user',
        ),
    ]
