# Generated by Django 3.0.4 on 2020-03-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('telefono', models.IntegerField(max_length=11)),
                ('numero_manzana', models.IntegerField(max_length=3)),
                ('numero_casa', models.IntegerField(max_length=2)),
                ('bloqueo', models.BooleanField(null=True)),
            ],
        ),
    ]
