# Generated by Django 3.0.4 on 2020-03-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='numero_casa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='numero_manzana',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
