# Generated by Django 3.0.4 on 2020-03-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_auto_20200308_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanagement',
            name='numero_casa',
        ),
        migrations.RemoveField(
            model_name='usermanagement',
            name='numero_manzana',
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='nivelAcceso',
            field=models.CharField(choices=[('NU', 'Normal'), ('NL', 'Limitado')], default='NU', max_length=2),
        ),
    ]
