# Generated by Django 3.0.4 on 2020-03-09 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userHome', '0001_initial'),
        ('userManagement', '0003_auto_20200309_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanagement',
            name='casa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userHome.UserHome'),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='bloqueo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='nivelAcceso',
            field=models.CharField(choices=[('NA', 'Administrador'), ('NU', 'Normal'), ('NL', 'Limitado')], default='NU', max_length=3),
        ),
    ]
