# Generated by Django 3.0.4 on 2020-05-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.DateTimeField(auto_now_add=True)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='nums.Number')),
            ],
            options={
                'ordering': ['-opened'],
            },
        ),
    ]
