# Generated by Django 3.1b1 on 2020-07-20 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.PositiveIntegerField(default=0, max_length=1, verbose_name='Codigo de Error')),
                ('method', models.CharField(choices=[('0', 'WEB'), ('1', 'GSM')], default='0', max_length=1, verbose_name='Metodo de acceso')),
                ('opening_date', models.DateField(auto_now_add=True, verbose_name='Registro de fecha')),
                ('opening_time', models.TimeField(auto_now_add=True, verbose_name='Registro de Hora')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='nums.number')),
            ],
        ),
    ]
