# Generated by Django 3.1b1 on 2020-07-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='method',
            field=models.IntegerField(null=True, verbose_name='Metodo de acceso'),
        ),
    ]
