# Generated by Django 3.1b1 on 2020-07-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='error',
            field=models.PositiveIntegerField(default=0, verbose_name='Codigo de Error'),
        ),
    ]
