# Generated by Django 3.0.4 on 2020-03-07 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20200307_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='user_id',
            new_name='number_id',
        ),
    ]
