# Generated by Django 3.0.4 on 2020-05-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residenceName', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre de residencia')),
                ('streetBlockNumber', models.CharField(max_length=10, null=True, verbose_name='Numero de manzana')),
                ('homeNumber', models.CharField(max_length=4, null=True, verbose_name='Numero de casa')),
            ],
        ),
    ]
