# Generated by Django 3.0.4 on 2020-05-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userHome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhome',
            name='homeNumber',
            field=models.CharField(default='Error', max_length=4, verbose_name='Numero de casa'),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='residenceName',
            field=models.CharField(default='Error', max_length=30, verbose_name='Nombre de residencia'),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='streetBlockNumber',
            field=models.CharField(default='Error', max_length=10, verbose_name='Numero de manzana'),
        ),
    ]
