# Generated by Django 3.0.4 on 2020-03-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userHome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhome',
            name='nombreResidencia',
        ),
        migrations.RemoveField(
            model_name='userhome',
            name='numeroCasa',
        ),
        migrations.RemoveField(
            model_name='userhome',
            name='numeroManzana',
        ),
        migrations.AddField(
            model_name='userhome',
            name='homeNumber',
            field=models.CharField(max_length=4, null=True, verbose_name='Numero de casa'),
        ),
        migrations.AddField(
            model_name='userhome',
            name='residenceName',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre de residencia'),
        ),
        migrations.AddField(
            model_name='userhome',
            name='streetBlockNumber',
            field=models.CharField(max_length=10, null=True, verbose_name='Numero de manzana'),
        ),
    ]
