# Generated by Django 3.0.4 on 2020-03-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userHome', '0003_userhome_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhome',
            name='userData',
        ),
    ]
