# Generated by Django 3.0.4 on 2020-03-23 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userHome', '0005_userhome_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhome',
            name='user',
        ),
    ]
